/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * SHDLC-Generator: 0.8.2
 * Yaml Version: 0.4.0
 * Template Version: 0.7.0-20-gf035cde
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sensirion_common.h"
#include "sensirion_shdlc.h"
#include "sensirion_test_setup.h"
#include "sensirion_uart_hal.h"
#include "svm41_uart.h"
#include <inttypes.h>
#include <stdio.h>

// TODO: DRIVER_GENERATOR Remove commands which shouldn't be tested
// TODO: DRIVER_GENERATOR Adjust setup and teardown
// TODO: DRIVER_GENERATOR Adjust all tests such that pre- and post conditions
// are met

TEST_GROUP (SVM41_Tests) {
    void setup() {
        int16_t error;
        error = sensirion_uart_hal_init();
        // TODO: DRIVER_GENERATOR Adjust UART port as soon as LKD-364 is done
        CHECK_EQUAL_ZERO_TEXT(error, "sensirion_uart_hal_init");
    }

    void teardown() {
        int16_t error;

        error = svm41_device_reset();
        CHECK_EQUAL_ZERO_TEXT(error, "svm41_device_reset");

        error = sensirion_uart_hal_free();
        CHECK_EQUAL_ZERO_TEXT(error, "sensirion_uart_hal_free");
    }
};

TEST (SVM41_Tests, SVM41_Test_start_measurement) {
    int16_t error;
    error = svm41_start_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_start_measurement");
}

TEST (SVM41_Tests, SVM41_Test_stop_measurement) {
    int16_t error;
    error = svm41_stop_measurement();
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_stop_measurement");
}

TEST (SVM41_Tests, SVM41_Test_read_measured_values_as_integers) {
    int16_t error;
    int16_t humidity;
    int16_t temperature;
    int16_t voc_index;
    int16_t nox_index;
    error = svm41_read_measured_values_as_integers(&humidity, &temperature,
                                                   &voc_index, &nox_index);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_read_measured_values_as_integers");
    printf("Humidity: %i\n", humidity);
    printf("Temperature: %i\n", temperature);
    printf("Voc index: %i\n", voc_index);
    printf("Nox index: %i\n", nox_index);
}

TEST (SVM41_Tests, SVM41_Test_read_measured_raw_values) {
    int16_t error;
    int16_t raw_humidity;
    int16_t raw_temperature;
    uint16_t raw_voc_ticks;
    uint16_t raw_nox_ticks;
    error = svm41_read_measured_raw_values(&raw_humidity, &raw_temperature,
                                           &raw_voc_ticks, &raw_nox_ticks);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_read_measured_raw_values");
    printf("Raw humidity: %i\n", raw_humidity);
    printf("Raw temperature: %i\n", raw_temperature);
    printf("Raw voc ticks: %u\n", raw_voc_ticks);
    printf("Raw nox ticks: %u\n", raw_nox_ticks);
}

TEST (SVM41_Tests, SVM41_Test_get_temperature_offset_for_rht_measurements) {
    int16_t error;
    uint8_t t_offset[42];
    uint8_t t_offset_size = 42;
    error = svm41_get_temperature_offset_for_rht_measurements(&t_offset[0],
                                                              t_offset_size);
    CHECK_EQUAL_ZERO_TEXT(error,
                          "svm41_get_temperature_offset_for_rht_measurements");
    printf("T offset: ");
    for (size_t i = 0; i < t_offset_size; i++) {
        printf("%u, ", t_offset[i]);
    }
    printf("\n");
}

TEST (SVM41_Tests, SVM41_Test_get_voc_tuning_parameters) {
    int16_t error;
    int16_t voc_index_offset;
    int16_t learning_time_offset_hours;
    int16_t learning_time_gain_hours;
    int16_t gating_max_duration_minutes;
    int16_t std_initial;
    error = svm41_get_voc_tuning_parameters(
        &voc_index_offset, &learning_time_offset_hours,
        &learning_time_gain_hours, &gating_max_duration_minutes, &std_initial);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_voc_tuning_parameters");
    printf("Voc index offset: %i\n", voc_index_offset);
    printf("Learning time offset hours: %i\n", learning_time_offset_hours);
    printf("Learning time gain hours: %i\n", learning_time_gain_hours);
    printf("Gating max duration minutes: %i\n", gating_max_duration_minutes);
    printf("Std initial: %i\n", std_initial);
}

TEST (SVM41_Tests, SVM41_Test_get_nox_tuning_parameters) {
    int16_t error;
    int16_t nox_index_offset;
    int16_t learning_time_offset_hours;
    int16_t learning_time_gain_hours;
    int16_t gating_max_duration_minutes;
    int16_t std_initial;
    error = svm41_get_nox_tuning_parameters(
        &nox_index_offset, &learning_time_offset_hours,
        &learning_time_gain_hours, &gating_max_duration_minutes, &std_initial);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_nox_tuning_parameters");
    printf("Nox index offset: %i\n", nox_index_offset);
    printf("Learning time offset hours: %i\n", learning_time_offset_hours);
    printf("Learning time gain hours: %i\n", learning_time_gain_hours);
    printf("Gating max duration minutes: %i\n", gating_max_duration_minutes);
    printf("Std initial: %i\n", std_initial);
}

TEST (SVM41_Tests, SVM41_Test_store_nv_data) {
    int16_t error;
    error = svm41_store_nv_data();
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_store_nv_data");
}

TEST (SVM41_Tests, SVM41_Test_set_temperature_offset_for_rht_measurements) {
    int16_t error;
    uint8_t t_offset[42];
    uint8_t t_offset_size = 42;
    error = svm41_set_temperature_offset_for_rht_measurements(&t_offset[0],
                                                              t_offset_size);
    CHECK_EQUAL_ZERO_TEXT(error,
                          "svm41_set_temperature_offset_for_rht_measurements");
}

TEST (SVM41_Tests, SVM41_Test_set_voc_tuning_parameters) {
    int16_t error;
    int16_t voc_index_offset = 0;
    int16_t learning_time_offset_hours = 0;
    int16_t learning_time_gain_hours = 0;
    int16_t gating_max_duration_minutes = 0;
    int16_t std_initial = 0;
    error = svm41_set_voc_tuning_parameters(
        voc_index_offset, learning_time_offset_hours, learning_time_gain_hours,
        gating_max_duration_minutes, std_initial);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_set_voc_tuning_parameters");
}

TEST (SVM41_Tests, SVM41_Test_set_nox_tuning_parameters) {
    int16_t error;
    int16_t nox_index_offset = 0;
    int16_t learning_time_offset_hours = 0;
    int16_t learning_time_gain_hours = 0;
    int16_t gating_max_duration_minutes = 0;
    int16_t std_initial = 0;
    error = svm41_set_nox_tuning_parameters(
        nox_index_offset, learning_time_offset_hours, learning_time_gain_hours,
        gating_max_duration_minutes, std_initial);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_set_nox_tuning_parameters");
}

TEST (SVM41_Tests, SVM41_Test_get_voc_state) {
    int16_t error;
    uint8_t state[42];
    uint8_t state_size = 42;
    error = svm41_get_voc_state(&state[0], state_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_voc_state");
    printf("State: ");
    for (size_t i = 0; i < state_size; i++) {
        printf("%u, ", state[i]);
    }
    printf("\n");
}

TEST (SVM41_Tests, SVM41_Test_get_nox_state) {
    int16_t error;
    uint8_t state[42];
    uint8_t state_size = 42;
    error = svm41_get_nox_state(&state[0], state_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_nox_state");
    printf("State: ");
    for (size_t i = 0; i < state_size; i++) {
        printf("%u, ", state[i]);
    }
    printf("\n");
}

TEST (SVM41_Tests, SVM41_Test_set_voc_state) {
    int16_t error;
    uint8_t state[42];
    uint8_t state_size = 42;
    error = svm41_set_voc_state(&state[0], state_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_set_voc_state");
}

TEST (SVM41_Tests, SVM41_Test_set_nox_state) {
    int16_t error;
    uint8_t state[42];
    uint8_t state_size = 42;
    error = svm41_set_nox_state(&state[0], state_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_set_nox_state");
}

TEST (SVM41_Tests, SVM41_Test_get_product_type) {
    int16_t error;
    unsigned char product_type[42];
    uint8_t product_type_size = 42;
    error = svm41_get_product_type(&product_type[0], product_type_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_product_type");
    printf("Product type: %s\n", product_type);
}

TEST (SVM41_Tests, SVM41_Test_get_product_name) {
    int16_t error;
    unsigned char product_name[42];
    uint8_t product_name_size = 42;
    error = svm41_get_product_name(&product_name[0], product_name_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_product_name");
    printf("Product name: %s\n", product_name);
}

TEST (SVM41_Tests, SVM41_Test_get_serial_number) {
    int16_t error;
    unsigned char serial_number[42];
    uint8_t serial_number_size = 42;
    error = svm41_get_serial_number(&serial_number[0], serial_number_size);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_serial_number");
    printf("Serial number: %s\n", serial_number);
}

TEST (SVM41_Tests, SVM41_Test_get_version) {
    int16_t error;
    uint8_t firmware_major;
    uint8_t firmware_minor;
    bool firmware_debug;
    uint8_t hardware_major;
    uint8_t hardware_minor;
    uint8_t protocol_major;
    uint8_t protocol_minor;
    error = svm41_get_version(&firmware_major, &firmware_minor, &firmware_debug,
                              &hardware_major, &hardware_minor, &protocol_major,
                              &protocol_minor);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_version");
    printf("Firmware major: %u\n", firmware_major);
    printf("Firmware minor: %u\n", firmware_minor);
    printf("Firmware debug: %i\n", firmware_debug);
    printf("Hardware major: %u\n", hardware_major);
    printf("Hardware minor: %u\n", hardware_minor);
    printf("Protocol major: %u\n", protocol_major);
    printf("Protocol minor: %u\n", protocol_minor);
}

TEST (SVM41_Tests, SVM41_Test_device_reset) {
    int16_t error;
    error = svm41_device_reset();
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_device_reset");
}

TEST (SVM41_Tests, SVM41_Test_get_system_up_time) {
    int16_t error;
    uint32_t system_up_time;
    error = svm41_get_system_up_time(&system_up_time);
    CHECK_EQUAL_ZERO_TEXT(error, "svm41_get_system_up_time");
    printf("System up time: %u\n", system_up_time);
}
