/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.33.0
 * Product:       svm4x
 * Model-Version: 2.0.2
 */
/*
 * Copyright (c) 2023, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_uart_hal.h"
#include "svm4x_uart.h"
#include <stdio.h>  // printf

#define sensirion_hal_sleep_us sensirion_uart_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;

    // for non linux systems modify the header file sensirion_uart_descriptor.h
    // SERIAL_0 defaults to "/dev/ttyUSB0" for linux user space implementation
    sensirion_uart_hal_init(SERIAL_0);

    error = svm4x_device_reset();
    if (error != NO_ERROR) {
        printf("error executing device_reset(): %i\n", error);
        return error;
    }
    sensirion_hal_sleep_us(2000000);
    int16_t voc_index_offset = 0;
    int16_t learning_time_offset_hours = 0;
    int16_t learning_time_gain_hours = 0;
    int16_t gating_max_duration_minutes = 0;
    int16_t std_initial = 0;
    int16_t gain_factor = 0;
    int16_t nox_index_offset = 0;
    error = svm4x_get_voc_tuning_parameters(
        &voc_index_offset, &learning_time_offset_hours,
        &learning_time_gain_hours, &gating_max_duration_minutes, &std_initial,
        &gain_factor);
    if (error != NO_ERROR) {
        printf("error executing get_voc_tuning_parameters(): %i\n", error);
        return error;
    }
    printf("voc_index_offset: %i ", voc_index_offset);
    printf("learning_time_offset_hours: %i ", learning_time_offset_hours);
    printf("learning_time_gain_hours: %i ", learning_time_gain_hours);
    printf("gating_max_duration_minutes: %i ", gating_max_duration_minutes);
    printf("std_initial: %i ", std_initial);
    printf("gain_factor: %i\n", gain_factor);
    error = svm4x_get_nox_tuning_parameters(
        &nox_index_offset, &learning_time_offset_hours,
        &learning_time_gain_hours, &gating_max_duration_minutes, &std_initial,
        &gain_factor);
    if (error != NO_ERROR) {
        printf("error executing get_nox_tuning_parameters(): %i\n", error);
        return error;
    }
    printf("nox_index_offset: %i ", nox_index_offset);
    printf("learning_time_offset_hours: %i ", learning_time_offset_hours);
    printf("learning_time_gain_hours: %i ", learning_time_gain_hours);
    printf("gating_max_duration_minutes: %i ", gating_max_duration_minutes);
    printf("std_initial: %i ", std_initial);
    printf("gain_factor: %i\n", gain_factor);
    error = svm4x_set_voc_tuning_parameters(100, 12, 12, 180, 50, 230);
    if (error != NO_ERROR) {
        printf("error executing set_voc_tuning_parameters(): %i\n", error);
        return error;
    }
    error = svm4x_set_nox_tuning_parameters(1, 12, 12, 720, 50, 230);
    if (error != NO_ERROR) {
        printf("error executing set_nox_tuning_parameters(): %i\n", error);
        return error;
    }
    error = svm4x_start_measurement();
    if (error != NO_ERROR) {
        printf("error executing start_measurement(): %i\n", error);
        return error;
    }
    int16_t humidity = 0;
    int16_t temperature = 0;
    int16_t voc_index = 0;
    int16_t nox_index = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 50; repetition++) {
        sensirion_hal_sleep_us(1000000);
        error = svm4x_read_measured_values_as_integers(&humidity, &temperature,
                                                       &voc_index, &nox_index);
        if (error != NO_ERROR) {
            printf("error executing read_measured_values_as_integers(): %i\n",
                   error);
            continue;
        }
        printf("humidity: %i ", humidity);
        printf("temperature: %i ", temperature);
        printf("voc_index: %i ", voc_index);
        printf("nox_index: %i\n", nox_index);
    }

    error = svm4x_stop_measurement();
    if (error != NO_ERROR) {
        return error;
    }
    return NO_ERROR;
}
